#!/usr/bin/env bash
# Generate Sources/ClaudeWeb/BuildInfo.swift with current git/build metadata.
# Called by deploy.sh BEFORE xcodegen so the .swift file is included in the
# regenerated project.
#
# Build counter persists in ~/.claude-web/ios-build-counter (auto-increments).
# Setting BUILD_NUMBER env override skips the counter (useful for CI).

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BUILDINFO_PATH="$PROJECT_DIR/Sources/ClaudeWeb/BuildInfo.swift"
COUNTER_FILE="${HOME}/.claude-web/ios-build-counter"

# 1) Auto-increment build counter (or use override).
if [[ -n "${BUILD_NUMBER:-}" ]]; then
  BUILD_NUM="$BUILD_NUMBER"
else
  mkdir -p "$(dirname "$COUNTER_FILE")"
  if [[ -f "$COUNTER_FILE" ]]; then
    BUILD_NUM=$(($(cat "$COUNTER_FILE") + 1))
  else
    BUILD_NUM=10
  fi
  echo "$BUILD_NUM" > "$COUNTER_FILE"
fi

# 2) Git metadata (best-effort; fall back to "unknown" outside a checkout).
GIT_SHA="$(git -C "$PROJECT_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"
GIT_DIRTY=""
if ! git -C "$PROJECT_DIR" diff --quiet 2>/dev/null; then GIT_DIRTY="+dirty"; fi
if ! git -C "$PROJECT_DIR" diff --cached --quiet 2>/dev/null; then GIT_DIRTY="+dirty"; fi
GIT_COMMIT_TIME="$(git -C "$PROJECT_DIR" log -1 --format=%cI 2>/dev/null || echo unknown)"
GIT_COMMIT_SUBJECT="$(git -C "$PROJECT_DIR" log -1 --format=%s 2>/dev/null | head -c 100 | iconv -c -f UTF-8 -t UTF-8 | sed 's/"/\\"/g' || echo unknown)"

# 3) Build time.
BUILD_TIME="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

# 4) Marketing version from project.yml (single source of truth).
MARKETING_VERSION="$(grep -E '^\s+MARKETING_VERSION:' "$PROJECT_DIR/project.yml" | sed -E 's/.*"([^"]+)".*/\1/' || echo "0.0.0")"

# 5) Update CURRENT_PROJECT_VERSION in project.yml so xcodegen embeds the right
# value in Info.plist (CFBundleVersion). xcodegen reads project.yml every run.
PYAML="$PROJECT_DIR/project.yml"
TMP="$(mktemp)"
awk -v ver="$BUILD_NUM" '
  /^[[:space:]]+CURRENT_PROJECT_VERSION:/ {
    sub(/"[^"]*"/, "\"" ver "\"")
  }
  { print }
' "$PYAML" > "$TMP" && mv "$TMP" "$PYAML"

# 6) Generate BuildInfo.swift (overwrite each time; not committed — see .gitignore).
cat > "$BUILDINFO_PATH" <<EOF
// AUTO-GENERATED by scripts/buildinfo.sh — DO NOT EDIT MANUALLY.
// Regenerated on every \`bash scripts/deploy.sh\` invocation.
// Listed in .gitignore so it doesn't pollute commits.

import Foundation

enum BuildInfo {
    static let marketingVersion = "$MARKETING_VERSION"
    static let buildNumber = "$BUILD_NUM"
    static let gitSha = "$GIT_SHA$GIT_DIRTY"
    static let gitCommitTime = "$GIT_COMMIT_TIME"
    static let gitCommitSubject = "$GIT_COMMIT_SUBJECT"
    static let buildTime = "$BUILD_TIME"

    /// Compact human-friendly summary for Settings page / logs.
    /// Example: "Seaidea 0.2.2 (build 47) · a3f2c4b · 2026-05-02 21:15"
    static var summary: String {
        "Seaidea \(marketingVersion) (build \(buildNumber)) · \(gitSha) · \(buildTime.prefix(16).replacingOccurrences(of: "T", with: " "))"
    }
}
EOF

echo "[buildinfo] generated v$MARKETING_VERSION+$BUILD_NUM ($GIT_SHA$GIT_DIRTY) at $BUILD_TIME"
